/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.den.lesson2;

public final class R {
    public static final class attr {
    }
    public static final class string {
        public static final int app_name=0x7f020000;
        public static final int back=0x7f020004;
        public static final int email=0x7f020001;
        public static final int login=0x7f020003;
        public static final int password=0x7f020002;
    }
}
